Added couple of DirectX resources
GraphicsProgramming/resources pull request #10
Opened 2020-07-02 15:38 UTC by rednewt

I added some DirectX resources, namely, 3Dgep and bell0bytes.

2020-07-02 17:02 UTC, nickclark2016 requested changes

2020-07-02 17:02 UTC, nickclark2016 commented on index.html
> +		* [bell0bytes blog - DirectX Fundamentals](https://bell0bytes.eu/direct-x-com/)
Make it all alphabetical please

2020-07-02 18:11 UTC, nickclark2016 approved these changes

2020-07-02 18:45 UTC, DethRaid commented
Probably worth adding MSDN https://docs.microsoft.com/en-us/windows/win32/api/_direct3d12/ to the list of D3D resoruces

2020-07-02 18:54 UTC, Pitj3 approved these changes
Yep, this is fine

2020-07-03 00:07 UTC, merged

2020-07-03 12:40 UTC, rednewt commented
> Probably worth adding MSDN https://docs.microsoft.com/en-us/windows/win32/api/_direct3d12/ to the list of D3D resoruces

I think MSDN is easily searchable by Google and everyone would know about it, we should keep the list limited to hard to find resources.