Add docs.gl to resources
GraphicsProgramming/resources pull request #53
Opened 2021-08-08 01:36 UTC by bubba2k

docs.gl is a super nifty website I wouldn't want to go without when fiddling with OpenGL.

2021-08-08 15:40 UTC, nickclark2016 requested changes

2021-08-08 15:40 UTC, nickclark2016 commented on resources/index.html
> +		* [docs.gl - OpenGL API Documentation](http://docs.gl/)
We have the resources in alphabetical order for easy lookup.

2021-08-08 21:18 UTC, bubba2k commented
Done!

2021-08-09 11:22 UTC, deccer approved these changes
Looks good to me now.

2021-08-09 11:29 UTC, nickclark2016 approved these changes

2021-08-09 11:29 UTC, nickclark2016 commented
Approved and merging.

2021-08-09 11:30 UTC, merged